name: Publish Python package to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  build-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"

      - name: Install dependencies
        run: |
          uv tool install invoke
          inv env.init-dev --no-pre-commit

      - name: Build package
        run: |
          inv build.dist

      - name: Upload package distributions
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/
          if-no-files-found: error

  publish-pypi-package:
    needs: build-package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pelican-stat
    permissions:
      id-token: write
    steps:
      - name: Download package distributions
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
